GET http://localhost:3001/api/persons

###

DELETE http://localhost:3001/api/persons/36730

###

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Rodrigo",
    "number": "1234567890"
}

###
GET http://localhost:3001/api/unkownendpoint
